/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_tubes;

import javax.swing.JOptionPane;
/**
 *
 * @author Adhi Jr
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboxmk1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblTHmk1 = new javax.swing.JLabel();
        lblTHmk2 = new javax.swing.JLabel();
        lblTHmn1 = new javax.swing.JLabel();
        lblTHmn2 = new javax.swing.JLabel();
        cboxmk2 = new javax.swing.JCheckBox();
        cboxmn1 = new javax.swing.JCheckBox();
        cboxmn2 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        lblTHjmlh = new javax.swing.JLabel();
        lblTHBayar = new javax.swing.JLabel();
        txtJlhmk1 = new javax.swing.JTextField();
        txtJlhmk2 = new javax.swing.JTextField();
        txtJlhmn1 = new javax.swing.JTextField();
        txtJlhmn2 = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Menu");

        jLabel2.setText("Makanan");

        jLabel3.setText("Jumlah");

        jLabel4.setText("Harga");

        jLabel5.setText("Total Harga");

        cboxmk1.setText("Ramen");
        cboxmk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxmk1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Rp.10.000,-");

        jLabel7.setText("Rp.15.000,-");

        jLabel8.setText("Rp.25.000,-");

        jLabel9.setText("Rp.40.000,-");

        lblTHmk1.setText("Rp.0,-");

        lblTHmk2.setText("Rp.0,-");

        lblTHmn1.setText("Rp.0,-");

        lblTHmn2.setText("Rp.0,-");

        cboxmk2.setText("Sushi");
        cboxmk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxmk2ActionPerformed(evt);
            }
        });

        cboxmn1.setText("Milkshake");
        cboxmn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxmn1ActionPerformed(evt);
            }
        });

        cboxmn2.setText("Cocktail");
        cboxmn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxmn2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Total");

        lblTHjmlh.setText("0 Porsi");

        lblTHBayar.setText("Rp.0,-");

        btnHitung.setText("Hitung");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboxmk1)
                    .addComponent(cboxmn1)
                    .addComponent(cboxmn2)
                    .addComponent(cboxmk2))
                .addGap(70, 70, 70)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(136, 136, 136)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnKembali))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addGap(0, 149, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addGap(100, 100, 100)
                                        .addComponent(jLabel3))
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTHjmlh)))
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtJlhmk2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJlhmk1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJlhmn1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJlhmn2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(btnHitung)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnReset)
                                        .addGap(27, 27, 27)))))
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTHBayar)
                                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblTHmk2)
                                        .addComponent(lblTHmk1)
                                        .addComponent(lblTHmn1)
                                        .addComponent(lblTHmn2)))))))
                .addGap(36, 36, 36))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxmk1)
                    .addComponent(jLabel6)
                    .addComponent(lblTHmk1)
                    .addComponent(txtJlhmk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblTHmk2)
                    .addComponent(cboxmk2)
                    .addComponent(txtJlhmk2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTHmn1)
                    .addComponent(cboxmn1)
                    .addComponent(txtJlhmn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblTHmn2)
                    .addComponent(cboxmn2)
                    .addComponent(txtJlhmn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblTHjmlh)
                    .addComponent(lblTHBayar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitung)
                    .addComponent(btnReset)
                    .addComponent(btnKembali))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private static void pesan_karakter(){
        JOptionPane.showMessageDialog(null, "Format Jumlah Makanan Harus Angka","Warning", JOptionPane.WARNING_MESSAGE);
    }
    private static void pesan_kosong(){
        JOptionPane.showMessageDialog(null, "Jumlah Pesanan Belum Dimasukkan","Warning", JOptionPane.WARNING_MESSAGE);
    }
    
    private void cboxmk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxmk1ActionPerformed
      if (cboxmk1.isSelected()== true){
           txtJlhmk1.setEditable(true);
           txtJlhmk1.requestFocus();
      }else {
           txtJlhmk1.setEditable(false);
           txtJlhmk1.setText("");
           lblTHmk1.setText("Rp.0,-");
       }
    }//GEN-LAST:event_cboxmk1ActionPerformed

    private void cboxmk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxmk2ActionPerformed
        if (cboxmk2.isSelected()== true){
           txtJlhmk2.setEditable(true);
           txtJlhmk2.requestFocus();
      }else {
           txtJlhmk2.setEditable(false);
           txtJlhmk2.setText("");
           lblTHmk2.setText("Rp.0,-");
       }
    }//GEN-LAST:event_cboxmk2ActionPerformed

    private void cboxmn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxmn1ActionPerformed
        if (cboxmn1.isSelected()== true){
           txtJlhmn1.setEditable(true);
           txtJlhmn1.requestFocus();
      }else {
           txtJlhmn1.setEditable(false);
           txtJlhmn1.setText("");
           lblTHmn1.setText("Rp.0,-");
       }
    }//GEN-LAST:event_cboxmn1ActionPerformed

    private void cboxmn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxmn2ActionPerformed
        if (cboxmn2.isSelected()== true){
           txtJlhmn2.setEditable(true);
           txtJlhmn2.requestFocus();
      }else {
           txtJlhmn2.setEditable(false);
           txtJlhmn2.setText("");
           lblTHmn2.setText("Rp.0,-");
       }
    }//GEN-LAST:event_cboxmn2ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
     txtJlhmk1.setEditable(false);
     txtJlhmk2.setEditable(false);
     txtJlhmn1.setEditable(false);
     txtJlhmn2.setEditable(false);
     cboxmk1.setSelected(false);
     cboxmk2.setSelected(false);
     cboxmn1.setSelected(false);
     cboxmn2.setSelected(false);
     txtJlhmk1.setText("");
     txtJlhmk2.setText("");
     txtJlhmn1.setText("");
     txtJlhmn2.setText("");
     lblTHjmlh.setText("0 porsi");
     lblTHmk1.setText("Rp. 0,-");
     lblTHmk2.setText("Rp. 0,-");
     lblTHmn1.setText("Rp. 0,-");
     lblTHmn2.setText("Rp. 0,-");
     lblTHBayar.setText("Rp. 0,-");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        this.dispose();
        new MenuPilihan().setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {
   int Jlhmk1  = 0,
       Jlhmk2  = 0,
       Jlhmn1  = 0,
       Jlhmn2  = 0,
       Hrgmk1  = 0,
       Hrgmk2  = 0,
       Hrgmn1  = 0,
       Hrgmn2  = 0,
       THmk1 = 0,THmk2 = 0,THmn1 = 0,THmn2 = 0,THJlh,THBayar;
   if (cboxmk1.isSelected() == false && cboxmk2.isSelected()==false && cboxmn1.isSelected()==false && cboxmn2.isSelected()==false){
       JOptionPane.showMessageDialog(null, "Makanan Belum Dipesan","Warning",JOptionPane.WARNING_MESSAGE);
   }
   else {
       if (cboxmk1.isSelected()==true){
          if (txtJlhmk1.getText().length()==0){
              pesan_kosong();
              txtJlhmk1.requestFocus();
          }
          else if (txtJlhmk1.getText().matches("[1-9]")){
              Jlhmk1    = Integer.parseInt(txtJlhmk1.getText());
              Hrgmk1    = 10000;
              THmk1 = Jlhmk1 * Hrgmk1;
              lblTHmk1.setText("Rp. "+THmk1+",-");
          }
          else {
              pesan_karakter();
              txtJlhmk1.requestFocus();
          }
       } 
       if (cboxmk2.isSelected()==true){
          if (txtJlhmk2.getText().length()==0){
              pesan_kosong();
              txtJlhmk2.requestFocus();
          }
          else if (txtJlhmk2.getText().matches("[1-9]")){
              Jlhmk2    = Integer.parseInt(txtJlhmk2.getText());
              Hrgmk2    = 15000;
              THmk2 = Jlhmk2 * Hrgmk2;
              lblTHmk2.setText("Rp. "+THmk2+",-");
          }
          else {
              pesan_karakter();
              txtJlhmk2.requestFocus();
          }
       } 
       if (cboxmn1.isSelected()==true){
          if (txtJlhmn1.getText().length()==0){
              pesan_kosong();
              txtJlhmn1.requestFocus();
          }
          else if (txtJlhmn1.getText().matches("[1-9]")){
              Jlhmn1    = Integer.parseInt(txtJlhmn1.getText());
              Hrgmn1    = 25000;
              THmn1 = Jlhmn1 * Hrgmn1;
              lblTHmn1.setText("Rp. "+THmn1+",-");
          }
          else {
              pesan_karakter();
              txtJlhmn1.requestFocus();
          }
       }       
       if (cboxmn2.isSelected()==true){
          if (txtJlhmn2.getText().length()==0){
              pesan_kosong();
              txtJlhmn2.requestFocus();
          }
          else if (txtJlhmn2.getText().matches("[1-9]")){
              Jlhmn2    = Integer.parseInt(txtJlhmn2.getText());
              Hrgmn2    = 40000;
              THmn2 = Jlhmn2 * Hrgmn2;
              lblTHmn2.setText("Rp. "+THmn2+",-");
          }
          else {
              pesan_karakter();
              txtJlhmn2.requestFocus();
          }
       }  
      
       THJlh   = THmk1 + THmk2 + THmn1 + THmn2;
       THBayar = Hrgmk1 + Hrgmk2 + Hrgmn1 + Hrgmn2;
       lblTHjmlh.setText(""+lblTHjmlh+"porsi");
       lblTHBayar.setText("Rp. "+lblTHBayar+",-");
   }
}
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Custumer().setVisible(true);
//        }
//    )
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox cboxmk1;
    private javax.swing.JCheckBox cboxmk2;
    private javax.swing.JCheckBox cboxmn1;
    private javax.swing.JCheckBox cboxmn2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblTHBayar;
    private javax.swing.JLabel lblTHjmlh;
    private javax.swing.JLabel lblTHmk1;
    private javax.swing.JLabel lblTHmk2;
    private javax.swing.JLabel lblTHmn1;
    private javax.swing.JLabel lblTHmn2;
    private javax.swing.JTextField txtJlhmk1;
    private javax.swing.JTextField txtJlhmk2;
    private javax.swing.JTextField txtJlhmn1;
    private javax.swing.JTextField txtJlhmn2;
    // End of variables declaration//GEN-END:variables

}
