/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_tubes;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JToggleButton;
import view_tubes.PesanBahan;
/**
 *
 * @author personal
 */
public class Pegawai extends javax.swing.JFrame {

    /**
     * Creates new form Pegawai
     */
    public Pegawai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        buttonPesanBahan = new javax.swing.JButton();
        buttonKelolaBahan = new javax.swing.JButton();
        buttonKelolaTransaksi = new javax.swing.JButton();
        buttonBuatLaporan = new javax.swing.JButton();
        ButtonKelolaMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("PEGAWAI");
        jLabel1.setToolTipText("");

        buttonPesanBahan.setText("Pesan Bahan");

        buttonKelolaBahan.setText("Kelola Bahan");

        buttonKelolaTransaksi.setText("Kelola Transaksi");

        buttonBuatLaporan.setText("Buat Laporan");

        ButtonKelolaMenu.setText("Kelola Menu");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(buttonPesanBahan)
                .addGap(18, 18, 18)
                .addComponent(buttonKelolaBahan)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(buttonKelolaTransaksi)
                        .addGap(18, 18, 18)
                        .addComponent(buttonBuatLaporan)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonKelolaMenu))
                    .addComponent(jLabel1))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonKelolaBahan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPesanBahan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuatLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonKelolaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonKelolaTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public JButton getbuttonPesanBahan() {
        return buttonPesanBahan;
    }

    public JButton getbuttonKelolaBahan() {
        return buttonKelolaBahan;
    }
    
    public JButton getbuttonKelolaTransaksi(){
        return buttonKelolaTransaksi;
    }
    
    public JButton getbuttonBuatLaporan(){
        return buttonBuatLaporan;
    }
    
    public JButton getbuttonKelolaMenu(){
        return ButtonKelolaMenu;
    }
    
     public void addActionListner(ActionListener e) {
        buttonPesanBahan.addActionListener(e);
        buttonKelolaBahan.addActionListener(e);
        buttonKelolaTransaksi.addActionListener(e);
        buttonBuatLaporan.addActionListener(e);
        ButtonKelolaMenu.addActionListener(e);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonKelolaMenu;
    private javax.swing.JButton buttonBuatLaporan;
    private javax.swing.JButton buttonKelolaBahan;
    private javax.swing.JButton buttonKelolaTransaksi;
    private javax.swing.JButton buttonPesanBahan;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
